import { ChatMessage } from "@org/api-contract";

export const messages: ChatMessage[] = [
  {
    id: "1",
    as: "john",
    content:
      "Hey! Did you know that turtles are attracted to cities because of the stronger light?",
    readAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "2",
    as: "melissa",
    content:
      "Really? I had no idea. I thought it was because of the natural light reflecting from the moon.",
    readAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "3",
    as: "john",
    content: "Nope, it's actually the artificial light that confuses them.",
    readAt: null,
    createdAt: new Date().toISOString(),
  },
  {
    id: "4",
    as: "melissa",
    content: "That's fascinating. Thanks for sharing!",
    readAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "5",
    as: "john",
    content: "No problem. I love learning about animals.",
    readAt: null,
    createdAt: new Date().toISOString(),
  },
  {
    id: "6",
    as: "melissa",
    content: "Me too. Did you know that turtles can live for over 100 years?",
    readAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "7",
    as: "john",
    content: "Yes, I did. They're such fascinating creatures.",
    readAt: null,
    createdAt: new Date().toISOString(),
  },
  {
    id: "8",
    as: "melissa",
    content: "I agree. I wish I could see one in the wild someday.",
    readAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "9",
    as: "john",
    content: "Me too. They're such beautiful animals.",
    readAt: null,
    createdAt: new Date().toISOString(),
  },
  {
    id: "10",
    as: "melissa",
    content: "I heard they're also a symbol of longevity and good luck in some cultures.",
    readAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "11",
    as: "john",
    content: "Yes, that's true. They're considered a sacred animal in some cultures.",
    readAt: null,
    createdAt: new Date().toISOString(),
  },
  {
    id: "12",
    as: "melissa",
    content: "I find it so interesting how different cultures view animals differently.",
    readAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "13",
    as: "john",
    content: "Yes, it's a fascinating aspect of anthropology.",
    readAt: null,
    createdAt: new Date().toISOString(),
  },
  {
    id: "14",
    as: "melissa",
    content: "I agree. It's one of the reasons I love studying it.",
    readAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "15",
    as: "john",
    content: "I'm glad we can have these conversations. They're always so interesting.",
    readAt: null,
    createdAt: new Date().toISOString(),
  },
  {
    id: "16",
    as: "melissa",
    content: "Me too. I always learn something new.",
    readAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "17",
    as: "john",
    content: "That's the best part, isn't it?",
    readAt: null,
    createdAt: new Date().toISOString(),
  },
  {
    id: "18",
    as: "melissa",
    content: "Definitely. I'm looking forward to our next chat.",
    readAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "19",
    as: "john",
    content: "Me too. Take care, Melissa.",
    readAt: null,
    createdAt: new Date().toISOString(),
  },
  {
    id: "20",
    as: "melissa",
    content: "You too, John. Bye for now.",
    readAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "21",
    as: "john",
    content: "Bye!",
    readAt: null,
    createdAt: new Date().toISOString(),
  },
  {
    id: "22",
    as: "melissa",
    content: "See you soon!",
    readAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "23",
    as: "john",
    content: "Definitely. I'm looking forward to our next chat.",
    readAt: null,
    createdAt: new Date().toISOString(),
  },
  {
    id: "24",
    as: "melissa",
    content: "Me too. Take care, Melissa.",
    readAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "25",
    as: "john",
    content: "You too, John. Bye for now.",
    readAt: null,
    createdAt: new Date().toISOString(),
  },
  {
    id: "26",
    as: "melissa",
    content: "Bye!",
    readAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "27",
    as: "john",
    content: "See you soon!",
    readAt: null,
    createdAt: new Date().toISOString(),
  },
];
